#!/bin/sh
# Usage: script/bootstrap
# Ensures all gems are installed locally.
set -e

git submodule update --init

bundle install

echo "\nRun './script/server' and point your browser to http://localhost:4001 to get started !\n"
